import time
import pyautogui

pyautogui.hotkey('alt', 'tab')
pyautogui.hotkey('ctrl', 'f')
time.sleep(1)
pyautogui.write('ZSD247')
time.sleep(1)
pyautogui.press('enter')
time.sleep(2)   
pyautogui.press('f2')
time.sleep(2)
pyautogui.write('**')
time.sleep(1)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(1)
pyautogui.write('0050053593')
time.sleep(1)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.write('01072022')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.write('31072022')
time.sleep(1)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.press('f8')
time.sleep(0.5)
pyautogui.hotkey('shift', 'space')
time.sleep(0.5)
pyautogui.press('f7')
time.sleep(1)
pyautogui.press('tab')
time.sleep(1)
pyautogui.write('373504')
time.sleep(2.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.press('down')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.write('301190')
time.sleep(0.5)
pyautogui.press('enter')
time.sleep(0.5)
pyautogui.hotkey('shift', 'space')
time.sleep(0.5)
pyautogui.hotkey('shift', 'f1')
time.sleep(0.5)
pyautogui.press('tab')
time.sleep(0.5)
pyautogui.hotkey('ctrl', 'tab')
time.sleep(0.5)
pyautogui.press('down')
time.sleep(0.5)
pyautogui.press('enter')






